### ISSUE TITLE
[Suggestion] Hide a member!

### ISSUE THREAD

**Issue by saeed2060** [PaulBender/Private-Message-Log#3]
Hey Paul.
I have a suggest.
Can add a option to this plugin for Hide a user from show in Private message log ?
Mean is:
Add a option to this plugin's setting for add user's ID and after add this, all of this user's PM are hide from private message log.
This can very useful for some admin like me :smile: this is possible or not?
Thanks.

**Comment by Sama34** [comment]
Rather it should be an on-script setting that MyBB setting, otherwise the same admin allowed to edit the setting could change it anyways to see hidden PMs so it would be pointless.

I'm assuming you don't want other admins to check your PMs or something.

**Comment by saeed2060** [comment]
Yeah but if we not access to other admin for edit script setting , can't change this ;)
In MyBB we can choose who member how much can access to Admin CP
This is Right?

**Comment by Sama34** [comment]
You are correct. However, it seems to be a trust issue, if  you can't trust them to not to check your PMs you can't trust them not to change the setting as well anyways.

**Comment by saeed2060** [comment]
Yeah it's very useful for me or some admins.
If this option add , I'm very happy.
Thanks.

**Comment by saeed2060** [comment]
Not anybody help me?!
Please PLEASE ! This is important for me , if anyone can , please help me :(

**Comment by saeed2060** [comment]
Thanks for not answer!!!
I add this with custom pay.
Closed.
